name: dart_2_files_json_to_arb
description: Combines two .json language files and converts them to .arb Flutter files.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: { args: ^2.3.1 }
